"""initial schema

Revision ID: 3f94e40d4cd0
Revises: 
Create Date: 2026-08-14 20:12:03.440309+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3f94e40d4cd0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id', 'ts'], unique=False)
    op.create_table('device_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=True),
    sa.Column('battery_at_event', sa.Integer(), nullable=True),
    sa.Column('network_at_event', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('msg_id', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_device_campaign', 'device_events', ['device_id', 'campaign_id', 'id'], unique=False)
    op.create_index('ix_events_ts', 'device_events', ['ts'], unique=False)
    op.create_index('uq_events_msg_id', 'device_events', ['msg_id'], unique=True, postgresql_where=sa.text('msg_id IS NOT NULL'))
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('hw_rev', sa.String(length=32), nullable=True),
    sa.Column('fleet_tag', sa.String(length=64), nullable=True),
    sa.Column('current_version', sa.String(length=32), nullable=True),
    sa.Column('current_version_code', sa.Integer(), nullable=False),
    sa.Column('min_allowed_version_code', sa.Integer(), nullable=False),
    sa.Column('active_slot', sa.String(length=8), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('network_quality', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('battery IS NULL OR (battery >= 0 AND battery <= 100)', name='ck_devices_battery_range'),
    sa.CheckConstraint('network_quality IS NULL OR (network_quality >= 1 AND network_quality <= 5)', name='ck_devices_network_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_index(op.f('ix_devices_fleet_tag'), 'devices', ['fleet_tag'], unique=False)
    op.create_index('ix_devices_online_seen', 'devices', ['online', 'last_seen_at'], unique=False)
    op.create_table('firmware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firmware_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('version_code', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('chunk_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firmware_id'),
    sa.UniqueConstraint('model', 'version', name='uq_firmware_model_version')
    )
    op.create_index('ix_firmware_state_model', 'firmware', ['state', 'model'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('firmware_id', sa.String(length=64), nullable=False),
    sa.Column('selector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('batch_size_initial', sa.Integer(), nullable=False),
    sa.Column('batch_size_min', sa.Integer(), nullable=False),
    sa.Column('batch_size_max', sa.Integer(), nullable=False),
    sa.Column('canary_size', sa.Integer(), nullable=False),
    sa.Column('shrink_threshold', sa.Float(), nullable=False),
    sa.Column('abort_threshold', sa.Float(), nullable=False),
    sa.Column('grow_after_clean_batches', sa.Integer(), nullable=False),
    sa.Column('ewma_alpha', sa.Float(), nullable=False),
    sa.Column('min_battery', sa.Integer(), nullable=False),
    sa.Column('min_network_quality', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('batch_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('current_batch_size', sa.Integer(), nullable=False),
    sa.Column('ewma_failure_rate', sa.Float(), nullable=False),
    sa.Column('clean_streak', sa.Integer(), nullable=False),
    sa.Column('batches_completed', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('batch_size_max >= batch_size_min', name='ck_campaign_max_batch'),
    sa.CheckConstraint('batch_size_min >= 1', name='ck_campaign_min_batch'),
    sa.CheckConstraint('shrink_threshold > 0 AND shrink_threshold <= abort_threshold AND abort_threshold <= 1', name='ck_campaign_thresholds'),
    sa.ForeignKeyConstraint(['firmware_id'], ['firmware.firmware_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_index('ix_campaigns_state', 'campaigns', ['state'], unique=False)
    op.create_table('device_health_samples',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=False),
    sa.Column('network_quality', sa.Integer(), nullable=False),
    sa.Column('uptime_s', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_device_ts', 'device_health_samples', ['device_id', 'ts'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('planned_size', sa.Integer(), nullable=False),
    sa.Column('actual_size', sa.Integer(), nullable=False),
    sa.Column('is_canary', sa.Boolean(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'index', name='uq_batch_campaign_index')
    )
    op.create_table('campaign_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_reason_code', sa.String(length=48), nullable=True),
    sa.Column('from_version', sa.String(length=32), nullable=True),
    sa.Column('to_version', sa.String(length=32), nullable=True),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('last_chunk_index', sa.Integer(), nullable=False),
    sa.Column('offer_nonce', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'device_id', name='uq_target_campaign_device')
    )
    op.create_index('ix_targets_campaign_state', 'campaign_targets', ['campaign_id', 'state'], unique=False)
    op.create_table('rollout_decisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('batch_index', sa.Integer(), nullable=False),
    sa.Column('prev_batch_size', sa.Integer(), nullable=False),
    sa.Column('new_batch_size', sa.Integer(), nullable=False),
    sa.Column('observed_failure_rate', sa.Float(), nullable=False),
    sa.Column('ewma_failure_rate', sa.Float(), nullable=False),
    sa.Column('attempted', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_campaign_ts', 'rollout_decisions', ['campaign_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decisions_campaign_ts', table_name='rollout_decisions')
    op.drop_table('rollout_decisions')
    op.drop_index('ix_targets_campaign_state', table_name='campaign_targets')
    op.drop_table('campaign_targets')
    op.drop_table('batches')
    op.drop_index('ix_health_device_ts', table_name='device_health_samples')
    op.drop_table('device_health_samples')
    op.drop_index('ix_campaigns_state', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_firmware_state_model', table_name='firmware')
    op.drop_table('firmware')
    op.drop_index('ix_devices_online_seen', table_name='devices')
    op.drop_index(op.f('ix_devices_fleet_tag'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('uq_events_msg_id', table_name='device_events', postgresql_where=sa.text('msg_id IS NOT NULL'))
    op.drop_index('ix_events_ts', table_name='device_events')
    op.drop_index('ix_events_device_campaign', table_name='device_events')
    op.drop_table('device_events')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
