#!/usr/bin/env python3
"""
CONVOY — firmware signing keypair generator.  Run ONCE, on the admin machine.

Why Ed25519
-----------
The device must verify a signature inside a constrained runtime. Ed25519
verification is ~2 ms on an ESP32 at 240 MHz and the public key is 32 bytes,
so it fits in flash and in the OTA time budget. RSA-2048 verification is an
order of magnitude slower and the key material is far larger.

Trust model (also documented inline in the server's crypto module)
------------------------------------------------------------------
The PRIVATE key never leaves this machine. It is not committed, not baked
into any Docker image, not shipped to any device, and not present in the
dashboard bundle. Devices hold ONLY the 32-byte public key, compiled into
their image at build/provisioning time.

An attacker who owns the network -- who can read and write any MQTT topic,
replay old messages, and impersonate the broker -- still cannot get firmware
installed, because installation requires a valid Ed25519 signature over a
manifest that binds the image hash, the device id, the campaign id, and a
server-issued nonce. Producing one without the private key is a signature
forgery (~2^128 work). TLS protects the channel, but the design deliberately
does not *depend* on the broker being honest.

Usage
-----
    pip install cryptography
    python tools/keygen.py --out admin/secrets
    python tools/keygen.py --out admin/secrets --c-header hardware/esp32-tcu/include/server_pubkey.h
"""

from __future__ import annotations

import argparse
import os
import stat
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


def write_c_header(pub_raw: bytes, path: Path) -> None:
    """Emit the public key as a C array for the ESP32 build."""
    body = ", ".join(f"0x{b:02X}" for b in pub_raw)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "// AUTO-GENERATED by tools/keygen.py -- do not edit by hand.\n"
        "// Server firmware-signing PUBLIC key. Safe to publish.\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        "static const uint8_t CONVOY_SERVER_PUBKEY[32] = {\n"
        f"    {body}\n"
        "};\n"
    )
    print(f"  wrote {path}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="admin/secrets", help="output directory")
    ap.add_argument("--c-header", default=None, help="also emit an ESP32 C header")
    ap.add_argument("--force", action="store_true", help="overwrite existing keys")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    priv_path = out / "convoy_ed25519_private.pem"
    pub_path = out / "convoy_ed25519_public.pem"
    pub_raw_path = out / "convoy_ed25519_public.raw"

    if priv_path.exists() and not args.force:
        raise SystemExit(
            f"refusing to overwrite {priv_path}. Re-signing with a new key would "
            f"invalidate every already-provisioned device. Use --force only if you "
            f"intend to re-provision the whole fleet."
        )

    key = Ed25519PrivateKey.generate()
    pub = key.public_key()

    priv_path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    os.chmod(priv_path, stat.S_IRUSR | stat.S_IWUSR)  # 0600 — owner only

    pub_path.write_bytes(
        pub.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
    )
    pub_raw = pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    pub_raw_path.write_bytes(pub_raw)

    print("keypair generated")
    print(f"  {priv_path}   (0600, NEVER leaves this machine, NEVER committed)")
    print(f"  {pub_path}    (safe to distribute)")
    print(f"  {pub_raw_path} (32 raw bytes, for embedding)")
    print(f"  public key hex: {pub_raw.hex()}")

    if args.c_header:
        write_c_header(pub_raw, Path(args.c_header))

    print("\nNext: confirm 'secrets/' is listed in .gitignore before you commit.")


if __name__ == "__main__":
    main()